/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package BusinessLayer.model;


import BusinessLayer.model.CompteId;
import BusinessLayer.model.Utilisateur;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name="compte"
    ,catalog="banque"
)
public class Compte  implements java.io.Serializable {

    
     private CompteId id;
     private Utilisateur utilisateur;
     private Date dateOuverture;
     private Double solde;
     private Set transactions = new HashSet(0);

    public Compte() {
    }

	
    public Compte(CompteId id, Utilisateur utilisateur) {
        this.id = id;
        this.utilisateur = utilisateur;
    }
    public Compte(CompteId id, Utilisateur utilisateur, Date dateOuverture, Double solde, Set transactions) {
       this.id = id;
       this.utilisateur = utilisateur;
       this.dateOuverture = dateOuverture;
       this.solde = solde;
       this.transactions = transactions;
    }
   
     @EmbeddedId

    @AttributeOverrides( {
        @AttributeOverride(name="idCompte", column=@Column(name="idCompte", nullable=false) ), 
        @AttributeOverride(name="utilisateurId", column=@Column(name="Utilisateur_id", nullable=false) ) } )
    public CompteId getId() {
        return this.id;
    }
    
    public void setId(CompteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Utilisateur_id", nullable=false, insertable=false, updatable=false)
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DateOuverture", length=10)
    public Date getDateOuverture() {
        return this.dateOuverture;
    }
    
    public void setDateOuverture(Date dateOuverture) {
        this.dateOuverture = dateOuverture;
    }

    
    @Column(name="Solde", precision=22, scale=0)
    public Double getSolde() {
        return this.solde;
    }
    
    public void setSolde(Double solde) {
        this.solde = solde;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compte")
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }




}


