/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BusinessLayer.model;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompteId generated by hbm2java
 */
@Embeddable
public class CompteId implements java.io.Serializable {

    private int idCompte;
    private int utilisateurId;

    public CompteId() {
    }

    public CompteId(int idCompte, int utilisateurId) {
        this.idCompte = idCompte;
        this.utilisateurId = utilisateurId;
    }

    @Column(name = "idCompte", nullable = false)
    public int getIdCompte() {
        return this.idCompte;
    }

    public void setIdCompte(int idCompte) {
        this.idCompte = idCompte;
    }

    @Column(name = "Utilisateur_id", nullable = false)
    public int getUtilisateurId() {
        return this.utilisateurId;
    }

    public void setUtilisateurId(int utilisateurId) {
        this.utilisateurId = utilisateurId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof CompteId)) {
            return false;
        }
        CompteId castOther = (CompteId) other;

        return (this.getIdCompte() == castOther.getIdCompte())
                && (this.getUtilisateurId() == castOther.getUtilisateurId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdCompte();
        result = 37 * result + this.getUtilisateurId();
        return result;
    }

}
